name: JoltingTrims
version: '${project.version}'
main: me.skript.joltingtrims.JoltingTrims
api-version: 1.20
authors: [ Skript ]
description: Your stylish way of selecting a new cool trim for your armor!
commands:
  trim:
    description: Main command of the armor trimming settings!
    usage: /<command>